spring:
  profile:
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 10
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rolwin?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Rolwin@2003
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: false
    show_sql: false
    generate-ddl: true
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      generate_statistics: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.time_zone: Asia/Kolkata


server:
  port: 8081
  undertow:
    enabled: true
    max-http-post-size: 20MB
    max-http-request-size: 20MB

logging:
  level.org.springframework.web: INFO

